<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CalendarWidget.Core\CalendarWidget.Core.csproj" />
    <ProjectReference Include="..\CalendarWidget.Infrastructure\CalendarWidget.Infrastructure.csproj" />
    <ProjectReference Include="..\CalendarWidget.Presentation\CalendarWidget.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <StartupObject>CalendarWidget.App.Program</StartupObject>
  </PropertyGroup>

</Project>
